import { useCallback, useEffect, useState } from 'react'
import RequestStatus from '../components/RequestStatus'
import Icon from '../components/Icon'
import api, { errorMessage } from '../services/api'

export default function AdminRequests() {
  const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [processing, setProcessing] = useState(null); const [comments, setComments] = useState({})
  const load = useCallback(() => { setLoading(true); api.get('/admin/requests').then(({ data }) => setRequests(data)).catch((err) => setError(errorMessage(err, 'Could not load requests.'))).finally(() => setLoading(false)) }, [])
  useEffect(() => { load() }, [load])
  const count = (status) => requests.filter((request) => request.status === status).length
  const decide = async (request, action) => { setProcessing(request.id); setError(''); try { await api.post(`/admin/requests/${request.id}/${action}`, { comment: comments[request.id] || '' }); await load() } catch (err) { setError(errorMessage(err, 'Request could not be processed.')) } finally { setProcessing(null) } }
  return <><div className="dashboard-heading"><div><p className="eyebrow">Administration workspace</p><h1>Student requests</h1><p>Review incoming document requests and record a clear decision.</p></div><span className="live-indicator"><i /> Workflow connected</span></div>
    <div className="stats-grid admin-stats"><div className="stat-card"><span className="stat-icon blue"><Icon name="inbox" /></span><div><strong>{requests.length}</strong><span>All requests</span></div></div><div className="stat-card"><span className="stat-icon amber"><Icon name="clock" /></span><div><strong>{count('Submitted')}</strong><span>Awaiting decision</span></div></div><div className="stat-card"><span className="stat-icon green"><Icon name="check" /></span><div><strong>{count('Approved')}</strong><span>Approved</span></div></div><div className="stat-card"><span className="stat-icon red"><Icon name="close" /></span><div><strong>{count('Rejected')}</strong><span>Rejected</span></div></div></div>
    <div className="section-heading queue-heading"><div><p className="eyebrow">Review queue</p><h2>All submissions</h2></div><span className="result-count">{requests.length} records</span></div>
    {loading && <div className="loading-panel"><span className="spinner" /> Loading student requests...</div>}{error && <div className="message error">{error}</div>}{!loading && requests.length === 0 && <div className="empty-state"><span><Icon name="inbox" size={30} /></span><h2>Queue is clear</h2><p>New student requests will appear here.</p></div>}
    <div className="admin-list">{requests.map((request) => <article className="admin-card" key={request.id}><header><div className="student-cell"><span className="avatar light">{request.studentName.charAt(0)}</span><div><strong>{request.studentName}</strong><span>{request.studentEmail}</span></div></div><RequestStatus status={request.status} /></header><div className="admin-card-body"><div className="document-cell"><span className="service-icon"><Icon name="document" /></span><div><span>Requested document</span><h2>{request.service}</h2></div></div><dl><div><dt>Submitted</dt><dd>{new Date(request.createdAt).toLocaleString()}</dd></div><div><dt>Student note</dt><dd>{request.note || 'No note provided'}</dd></div></dl></div>
      {request.status === 'Submitted' ? <footer className="decision"><label>Decision comment <span className="optional">Optional</span><textarea rows="2" maxLength="1000" placeholder="Add a helpful note for the student..." value={comments[request.id] || ''} onChange={(e) => setComments({ ...comments, [request.id]: e.target.value })} /></label><div className="actions"><button className="approve-button" disabled={processing === request.id} onClick={() => decide(request, 'approve')}><Icon name="check" size={18} />{processing === request.id ? 'Processing...' : 'Approve request'}</button><button className="danger" disabled={processing === request.id} onClick={() => decide(request, 'reject')}><Icon name="close" size={18} />Reject</button></div></footer> : <footer className="decision completed-decision"><span>Decision comment</span><strong>{request.adminComment || 'No comment provided'}</strong></footer>}
    </article>)}</div>
  </>
}
